apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thryvo-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - secretName: selfsigned
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pa-baseline-service
            port:
              number: 3000
