apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-authz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pa-authz
  template:
    metadata:
      labels:
        app: pa-authz
    spec:
      imagePullSecrets:
      - name: thryvo-secret
      containers:
      - name: pa-authz-container
        image: caxdevacrpa0.azurecr.io/cax_pa-authz_dev:5637
        ports:
        - containerPort: 3015
---
apiVersion: v1
kind: Service
metadata:
  name: pa-authz-service
spec:
  selector:
    app: pa-authz
  ports:
  - protocol: TCP
    port: 3015
    targetPort: 3015
    nodePort: 31002
  type: NodePort
