apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-baseline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pa-baseline
  template:
    metadata:
      labels:
        app: pa-baseline
    spec:
      imagePullSecrets:
      - name: thryvo-secret
      containers:
      - name: pa-baseline-container
        image: caxdevacrpa0.azurecr.io/cax_pa-baseline_dev:5636
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pa-baseline-service
spec:
  selector:
    app: pa-baseline
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
