apiVersion: v1
kind: Namespace
metadata:
  name: databases

---
# Using local storage for kubeadm cluster
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-mongodb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# Create PV using hostPath for local kubeadm cluster
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-mongodb
  local:
    path: /mnt/data/mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - YOUR_NODE_NAME  # Replace with actual node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-local-pvc
  namespace: databases
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage-mongodb
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: databases
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: caxdevacrpa0.azurecr.io/cax_mongo_dev:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password123
        ports:
        - containerPort: 27017
          name: mongo
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/data/db"
          name: mongodb-data
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-local-pvc
      imagePullSecrets:
      - name: thryvo-secret

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: databases
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
