apiVersion: apps/v1
kind: Deployment
metadata:
  name: thryvo-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thryvo-ui
  template:
    metadata:
      labels:
        app: thryvo-ui
    spec:
      imagePullSecrets:
      - name: thryvo-secret
      containers:
      - name: thryvo-ui-container
        image: caxdevacrpa0.azurecr.io/cax_shell_app_dev:5756
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: thryvo-ui-service
spec:
  selector:
    app: thryvo-ui
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31000
  type: NodePort
