apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-leavemodule-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pa-leavemodule
  template:
    metadata:
      labels:
        app: pa-leavemodule
    spec:
      imagePullSecrets:
      - name: thryvo-secret
      containers:
      - name: pa-leavemodule-container
        image: caxdevacrpa0.azurecr.io/cax_pa-leavemodule_dev:5714
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: pa-leavemodule-service
spec:
  selector:
    app: pa-leavemodule
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31004
  type: NodePort
